version: "3.8"
services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always  

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      # If you want to use the local mongo container instead of Atlas, change this to:
      # - MONGODB_URI=mongodb://mongo:27017/memories
      - MONGODB_URI=mongodb+srv://sarveshpco123:sarveshpco123123@cluster0.gn9pmuj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000  
    restart: always
