version: "3.8"
services:
  client:
    image: sarveshk0/memories-client:latest
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always  

  server:
    image: sarveshk0/memories-server:latest
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
